Repository eclipse/che-che4z-zos-resource-explorer, pull requests merged in 2019-08, with the labels that each got.

#7 Remove workaround with create connection node
  package.json
  src/ui/tree/DatasetDataProvider.ts
  src/ui/tree/DatasetTreeModel.ts
Labels: enhancement

#14 Use Webpack for packaging
  .gitignore
  .vscodeignore
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#15 browse PS dataset
  package.json
Labels: enhancement

#23 #22 Update main fiels and setup build jobs for webpack
  .vscode/launch.json
  .vscode/tasks.json
  package.json
Labels: bug

#31 #30 Add Jest for unit-test
  .gitignore
  .vscode/launch.json
  .vscodeignore
  jest.config.js
  package-lock.json
  package.json
  resources/editpanel.html
  src/__mocks__/vscode.ts
  src/__tests__/DatasetCache.test.ts
  src/__tests__/credential-service.test.ts
  src/__tests__/extension.test.ts
  src/service/DatasetCache.ts
  src/service/__mocks__/CredentialsService.ts
  src/service/__mocks__/SettingsFacade.ts
  src/service/__mocks__/ZoweRestClient.ts
  src/test/index.ts
Labels: enhancement

#33 Dataset edit manager suit test
  package-lock.json
  src/__mocks__/vscode.ts
  src/__tests__/datasetEditManager.test.ts
  src/extension.ts
  src/service/DatasetEditManager.ts
Labels: test
